# Gensim: LDA Topic Modeling using Gensim

In [1]:
%load_ext autoreload
%autoreload 2

import logging
import Gensim_topic_modeling_utils as topic_utils 


logging.basicConfig(level=logging.INFO)
_LOG = logging.getLogger(__name__)

_LOG.info("Setup complete")

/usr/local/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:__main__:Setup complete

In [2]:
import pandas as pd
import numpy as np

## Text Pre-processing

Before topic modeling, the text must be cleaned and converted into tokens which makes it easier for the model to understand the words

- **Tokenization**: split text into individual words
- **Stopword removal**: remove common words like "the", "is"
- **Lemmatization**: reduce words to base form ("running" → "run")

In [3]:
topic_utils.download_nltk_data()

In [4]:
sample_df = topic_utils.sample_dataset()
sample_df.head()

,title,content,topic_actual
0,ASIAN EXPORTERS FEAR DAMAGE FROM U.S.-JAPAN RIFT,Mounting trade friction between the U.S. And...,trade
1,THAI TRADE DEFICIT WIDENS IN FIRST QUARTER,Thailand's trade deficit widened to 4.5 bill...,trade
2,JAPAN MINISTRY SAYS OPEN FARM TRADE WOULD HIT ...,"Japan's Agriculture Ministry, angered by U.S...",trade
3,SOUTH KOREA MOVES TO SLOW GROWTH OF TRADE SURPLUS,South Korea's trade surplus is growing too f...,trade
4,JAPAN GIVEN LITTLE HOPE OF AVOIDING U.S. SANCT...,A top U.S. Official said Japan has little ch...,trade

In [5]:
sample_df.shape

(43, 3)

In [6]:
# Preprocess all documents 
processed_docs = topic_utils.preprocess_corpus(list(sample_df['content']))

print("Output tokens of the first sample document: \n",processed_docs[0])

Output tokens of the first sample document:
 ['mounting', 'trade', 'friction', 'japan', 'raised', 'fear', 'among', 'many', 'asia', 'exporting', 'nation', 'row', 'could', 'inflict', 'economic', 'damage', 'businessmen', 'official', 'said', 'told', 'reuter', 'correspondent', 'asian', 'capital', 'move', 'japan', 'might', 'boost', 'protectionist', 'sentiment', 'lead', 'curb', 'american', 'import', 'product', 'exporter', 'said', 'conflict', 'would', 'hurt', 'tokyo', 'loss', 'might', 'gain', 'said', 'impose', 'mln', 'dlrs', 'tariff', 'import', 'japanese', 'electronics', 'good', 'april', 'retaliation', 'japan', 'alleged', 'failure', 'stick', 'pact', 'sell', 'semiconductor', 'world', 'market', 'cost', 'unofficial', 'japanese', 'estimate', 'put', 'impact', 'tariff', 'billion', 'dlrs', 'spokesman', 'major', 'electronics', 'firm', 'said', 'would', 'virtually', 'halt', 'export', 'product', 'hit', 'new', 'tax', 'would', 'able', 'business', 'said', 'spokesman', 'leading', 'japanese', 'electronics', 'firm', 'matsushita', 'electric', 'industrial', 'co', 'ltd', 'lt', 'tariff', 'remain', 'place', 'length', 'time', 'beyond', 'month', 'mean', 'complete', 'erosion', 'export', 'good', 'subject', 'tariff', 'said', 'tom', 'murtha', 'stock', 'analyst', 'tokyo', 'office', 'broker', 'lt', 'james', 'capel', 'co', 'taiwan', 'businessmen', 'official', 'also', 'worried', 'aware', 'seriousness', 'threat', 'japan', 'serf', 'warning', 'u', 'said', 'senior', 'taiwanese', 'trade', 'official', 'asked', 'named', 'taiwan', 'trade', 'trade', 'surplus', 'billion', 'dlrs', 'last', 'year', 'pct', 'surplus', 'helped', 'swell', 'taiwan', 'foreign', 'exchange', 'reserve', 'billion', 'dlrs', 'among', 'world', 'largest', 'must', 'quickly', 'open', 'market', 'remove', 'trade', 'barrier', 'cut', 'import', 'tariff', 'allow', 'import', 'product', 'want', 'defuse', 'problem', 'possible', 'retaliation', 'said', 'paul', 'sheen', 'chairman', 'textile', 'exporter', 'lt', 'taiwan', 'safe', 'group', 'senior', 'official', 'south', 'korea', 'trade', 'promotion', 'association', 'said', 'trade', 'dispute', 'japan', 'might', 'also', 'lead', 'pressure', 'south', 'korea', 'whose', 'chief', 'export', 'similar', 'japan', 'last', 'year', 'south', 'korea', 'trade', 'surplus', 'billion', 'dlrs', 'billion', 'dlrs', 'malaysia', 'trade', 'officer', 'businessmen', 'said', 'tough', 'curb', 'japan', 'might', 'allow', 'producer', 'semiconductor', 'third', 'country', 'expand', 'sale', 'hong', 'kong', 'newspaper', 'alleged', 'japan', 'selling', 'semiconductor', 'electronics', 'manufacturer', 'share', 'view', 'businessmen', 'said', 'commercial', 'advantage', 'would', 'outweighed', 'pressure', 'block', 'import', 'view', 'said', 'lawrence', 'mill', 'federation', 'hong', 'kong', 'industry', 'whole', 'purpose', 'prevent', 'import', 'one', 'day', 'extended', 'source', 'much', 'serious', 'hong', 'kong', 'disadvantage', 'action', 'restraining', 'trade', 'said', 'last', 'year', 'hong', 'kong', 'biggest', 'export', 'market', 'accounting', 'pct', 'domestically', 'produced', 'export', 'australian', 'government', 'awaiting', 'outcome', 'trade', 'talk', 'japan', 'interest', 'concern', 'industry', 'minister', 'john', 'button', 'said', 'canberra', 'last', 'friday', 'kind', 'deterioration', 'trade', 'relation', 'two', 'country', 'major', 'trading', 'partner', 'serious', 'matter', 'button', 'said', 'said', 'australia', 'concern', 'centred', 'coal', 'beef', 'australia', 'two', 'largest', 'export', 'japan', 'also', 'significant', 'export', 'country', 'meanwhile', 'diplomatic', 'manoeuvre', 'solve', 'trade', 'continue', 'japan', 'ruling', 'liberal', 'democratic', 'party', 'yesterday', 'outlined', 'package', 'economic', 'measure', 'boost', 'japanese', 'economy', 'measure', 'proposed', 'include', 'large', 'supplementary', 'budget', 'record', 'public', 'work', 'spending', 'first', 'half', 'financial', 'year', 'also', 'call', 'spending', 'emergency', 'measure', 'stimulate', 'economy', 'despite', 'prime', 'minister', 'yasuhiro', 'nakasone', 'avowed', 'fiscal', 'reform', 'program', 'deputy', 'trade', 'representative', 'michael', 'smith', 'makoto', 'kuroda', 'japan', 'deputy', 'minister', 'international', 'trade', 'industry', 'miti', 'due', 'meet', 'washington', 'week', 'effort', 'end', 'dispute']

## Word dictionary and corpus

Gensim LDA requires two structures:

- **Dictionary**: maps every unique token to an integer ID
- **Corpus**: converts each document into a bag-of-words (BoW) vector, i.e. a list of `(token_id, count)` pairs

Filtering the dictionary removes tokens that are too rare or too common,
keeping only the most informative vocabulary.

In [7]:
# Build dictionary from processed documents
# no_below=2: token must appear in at least 2 docs
# no_above=0.85: token must not appear in more than 85% of docs
# keep_n=500: hard cap on vocabulary size
dictionary = topic_utils.build_dictionary(
    processed_docs,
    no_below=2,
    no_above=0.85,
    keep_n=500
)

# Convert each document to BoW representation
corpus = topic_utils.build_corpus(processed_docs, dictionary)

# Inspect BoW for first document
print("BoW for doc 1: \n", corpus[0])
# Each tuple is (token_id, count)

INFO:gensim.corpora.dictionary:adding document #0 to Dictionary<0 unique tokens: []>
INFO:gensim.corpora.dictionary:built Dictionary<1673 unique tokens: ['able', 'accounting', 'action', 'advantage', 'alleged']...> from 43 documents (total 6148 corpus positions)
INFO:gensim.utils:Dictionary lifecycle event {'msg': "built Dictionary<1673 unique tokens: ['able', 'accounting', 'action', 'advantage', 'alleged']...> from 43 documents (total 6148 corpus positions)", 'datetime': '2026-05-06T21:15:05.100602', 'gensim': '4.4.0', 'python': '3.12.13 (main, Apr 22 2026, 02:12:20) [GCC 14.2.0]', 'platform': 'Linux-6.12.76-linuxkit-aarch64-with-glibc2.41', 'event': 'created'}
INFO:gensim.corpora.dictionary:discarding 1173 tokens: [('accounting', 1), ('advantage', 1), ('alleged', 1), ('asian', 1), ('australian', 1), ('avowed', 1), ('awaiting', 1), ('aware', 1), ('beyond', 1), ('biggest', 1)]...
INFO:gensim.corpora.dictionary:keeping 500 tokens which were in no less than 2 and no more than 36 (=85.0%) documents
INFO:gensim.corpora.dictionary:resulting dictionary: Dictionary<500 unique tokens: ['able', 'action', 'allow', 'also', 'american']...>

Vocabulary before filtering : 1673
Vocabulary after filtering  : 500
BoW for doc 1:
 [(0, 1), (1, 1), (2, 2), (3, 4), (4, 1), (5, 2), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 2), (12, 1), (13, 1), (14, 5), (15, 1), (16, 2), (17, 1), (18, 1), (19, 1), (20, 1), (21, 2), (22, 2), (23, 1), (24, 1), (25, 1), (26, 3), (27, 1), (28, 1), (29, 1), (30, 2), (31, 1), (32, 1), (33, 1), (34, 2), (35, 6), (36, 1), (37, 2), (38, 2), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 7), (45, 1), (46, 1), (47, 1), (48, 2), (49, 1), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 2), (56, 1), (57, 1), (58, 1), (59, 1), (60, 1), (61, 1), (62, 6), (63, 1), (64, 1), (65, 3), (66, 1), (67, 1), (68, 1), (69, 12), (70, 4), (71, 1), (72, 3), (73, 1), (74, 1), (75, 2), (76, 4), (77, 1), (78, 2), (79, 1), (80, 1), (81, 3), (82, 1), (83, 2), (84, 1), (85, 1), (86, 1), (87, 3), (88, 1), (89, 3), (90, 1), (91, 1), (92, 3), (93, 1), (94, 1), (95, 1), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (101, 1), (102, 1), (103, 4), (104, 1), (105, 1), (106, 1), (107, 1), (108, 1), (109, 1), (110, 1), (111, 2), (112, 1), (113, 2), (114, 1), (115, 1), (116, 1), (117, 3), (118, 1), (119, 1), (120, 1), (121, 1), (122, 1), (123, 1), (124, 1), (125, 1), (126, 1), (127, 1), (128, 1), (129, 1), (130, 1), (131, 2), (132, 1), (133, 1), (134, 16), (135, 1), (136, 1), (137, 1), (138, 3), (139, 2), (140, 1), (141, 1), (142, 1), (143, 1), (144, 1), (145, 3), (146, 2), (147, 2), (148, 1), (149, 1), (150, 3), (151, 1), (152, 5), (153, 1), (154, 1), (155, 1), (156, 2), (157, 1), (158, 15), (159, 1), (160, 2), (161, 1), (162, 2), (163, 1), (164, 1), (165, 1), (166, 1), (167, 1), (168, 1), (169, 2), (170, 4), (171, 4), (172, 1)]

## Coherence Evaluation and Topic Selection

Choosing the right number of topics is critical. We use the **c_v coherence score** which measures how semantically similar the top words in each topic are.

- Higher coherence → more interpretable topics
- We train models for a range of topic counts and pick the one with the
  highest coherence score
- Look for a clear **peak** or **elbow** in the coherence curve

In [8]:
# Compute coherence for topic counts 2 through 6

model_list, coherence_values = topic_utils.compute_coherence_values(
    dictionary = dictionary,
    corpus     = corpus,
    docs    = processed_docs,
    start      = 2,
    limit      = 7,
    step       = 1
)

# Coherence scores for each topic size 

score_dict = {}
for i, cv in enumerate(coherence_values):
    score_dict[i+2] = cv
    print(f"Num topics: {i+2:2d} | Coherence: {cv:.4f}")

INFO:gensim.models.ldamodel:using autotuned alpha, starting with [np.float32(0.5), np.float32(0.5)]
INFO:gensim.models.ldamodel:using symmetric eta at 0.5
INFO:gensim.models.ldamodel:using serial LDA version on this node
INFO:gensim.models.ldamodel:running online (multi-pass) LDA training, 2 topics, 15 passes over the supplied corpus of 43 documents, updating model once every 43 documents, evaluating perplexity every 43 documents, iterating 50x with a convergence threshold of 0.001000
INFO:gensim.models.ldamodel:-6.662 per-word bound, 101.3 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 0, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.70158947), np.float32(0.79242766)]
INFO:gensim.models.ldamodel:topic #0 (0.702): 0.052*"said" + 0.042*"pct" + 0.017*"year" + 0.016*"february" + 0.016*"japan" + 0.014*"january" + 0.014*"sale" + 0.011*"market" + 0.011*"dlrs" + 0.010*"billion"
INFO:gensim.models.ldamodel:topic #1 (0.792): 0.050*"pct" + 0.035*"sale" + 0.033*"said" + 0.021*"trade" + 0.018*"billion" + 0.018*"january" + 0.017*"february" + 0.016*"dlrs" + 0.015*"year" + 0.010*"mln"
INFO:gensim.models.ldamodel:topic diff=0.741001, rho=1.000000
INFO:gensim.models.ldamodel:-5.757 per-word bound, 54.1 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 1, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.27268663), np.float32(0.3998296)]
INFO:gensim.models.ldamodel:topic #0 (0.273): 0.053*"said" + 0.038*"pct" + 0.019*"japan" + 0.014*"market" + 0.014*"trade" + 0.014*"year" + 0.012*"february" + 0.012*"january" + 0.010*"import" + 0.009*"japanese"
INFO:gensim.models.ldamodel:topic #1 (0.400): 0.052*"pct" + 0.038*"sale" + 0.032*"said" + 0.020*"billion" + 0.020*"february" + 0.019*"january" + 0.018*"trade" + 0.018*"dlrs" + 0.017*"year" + 0.011*"mln"
INFO:gensim.models.ldamodel:topic diff=0.219184, rho=0.577350
INFO:gensim.models.ldamodel:-5.686 per-word bound, 51.5 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 2, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.17628834), np.float32(0.2563063)]
INFO:gensim.models.ldamodel:topic #0 (0.176): 0.053*"said" + 0.032*"pct" + 0.022*"japan" + 0.019*"trade" + 0.016*"market" + 0.012*"import" + 0.011*"japanese" + 0.011*"year" + 0.009*"export" + 0.009*"ministry"
INFO:gensim.models.ldamodel:topic #1 (0.256): 0.057*"pct" + 0.039*"sale" + 0.032*"said" + 0.022*"february" + 0.022*"january" + 0.020*"billion" + 0.019*"year" + 0.018*"dlrs" + 0.015*"trade" + 0.012*"mln"
INFO:gensim.models.ldamodel:topic diff=0.181852, rho=0.500000
INFO:gensim.models.ldamodel:-5.635 per-word bound, 49.7 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 3, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.13091782), np.float32(0.17788997)]
INFO:gensim.models.ldamodel:topic #0 (0.131): 0.053*"said" + 0.025*"pct" + 0.024*"japan" + 0.022*"trade" + 0.016*"market" + 0.013*"import" + 0.012*"japanese" + 0.010*"export" + 0.010*"official" + 0.009*"ministry"
INFO:gensim.models.ldamodel:topic #1 (0.178): 0.061*"pct" + 0.040*"sale" + 0.032*"said" + 0.024*"february" + 0.024*"january" + 0.021*"billion" + 0.021*"year" + 0.019*"dlrs" + 0.013*"trade" + 0.013*"rose"
INFO:gensim.models.ldamodel:topic diff=0.162905, rho=0.447214
INFO:gensim.models.ldamodel:-5.596 per-word bound, 48.4 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 4, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.10694842), np.float32(0.14856452)]
INFO:gensim.models.ldamodel:topic #0 (0.107): 0.053*"said" + 0.026*"japan" + 0.024*"trade" + 0.019*"pct" + 0.017*"market" + 0.013*"import" + 0.013*"japanese" + 0.010*"export" + 0.010*"official" + 0.009*"ministry"
INFO:gensim.models.ldamodel:topic #1 (0.149): 0.065*"pct" + 0.040*"sale" + 0.033*"said" + 0.025*"february" + 0.025*"january" + 0.021*"year" + 0.021*"billion" + 0.019*"dlrs" + 0.013*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.112876, rho=0.408248
INFO:gensim.models.ldamodel:-5.576 per-word bound, 47.7 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 5, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.0933485), np.float32(0.13380685)]
INFO:gensim.models.ldamodel:topic #0 (0.093): 0.052*"said" + 0.027*"japan" + 0.025*"trade" + 0.017*"market" + 0.015*"pct" + 0.013*"import" + 0.013*"japanese" + 0.010*"export" + 0.010*"official" + 0.010*"ministry"
INFO:gensim.models.ldamodel:topic #1 (0.134): 0.067*"pct" + 0.040*"sale" + 0.033*"said" + 0.026*"february" + 0.025*"january" + 0.022*"year" + 0.021*"billion" + 0.019*"dlrs" + 0.014*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.083652, rho=0.377964
INFO:gensim.models.ldamodel:-5.564 per-word bound, 47.3 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 6, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.084129244), np.float32(0.12328559)]
INFO:gensim.models.ldamodel:topic #0 (0.084): 0.052*"said" + 0.028*"japan" + 0.026*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.012*"pct" + 0.011*"export" + 0.011*"official" + 0.010*"ministry"
INFO:gensim.models.ldamodel:topic #1 (0.123): 0.068*"pct" + 0.040*"sale" + 0.033*"said" + 0.026*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.014*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.064357, rho=0.353553
INFO:gensim.models.ldamodel:-5.556 per-word bound, 47.0 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 7, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.0773932), np.float32(0.115297765)]
INFO:gensim.models.ldamodel:topic #0 (0.077): 0.052*"said" + 0.029*"japan" + 0.027*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"pct" + 0.010*"ministry"
INFO:gensim.models.ldamodel:topic #1 (0.115): 0.069*"pct" + 0.040*"sale" + 0.034*"said" + 0.026*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.014*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.050767, rho=0.333333
INFO:gensim.models.ldamodel:-5.550 per-word bound, 46.8 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 8, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.071487814), np.float32(0.108586654)]
INFO:gensim.models.ldamodel:topic #0 (0.071): 0.052*"said" + 0.029*"japan" + 0.027*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.109): 0.070*"pct" + 0.040*"sale" + 0.034*"said" + 0.026*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.014*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.040533, rho=0.316228
INFO:gensim.models.ldamodel:-5.546 per-word bound, 46.7 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 9, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.067211404), np.float32(0.104733944)]
INFO:gensim.models.ldamodel:topic #0 (0.067): 0.052*"said" + 0.029*"japan" + 0.028*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.105): 0.070*"pct" + 0.040*"sale" + 0.034*"said" + 0.026*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.015*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.034157, rho=0.301511
INFO:gensim.models.ldamodel:-5.543 per-word bound, 46.6 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 10, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.06383542), np.float32(0.10136421)]
INFO:gensim.models.ldamodel:topic #0 (0.064): 0.051*"said" + 0.030*"japan" + 0.028*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.101): 0.071*"pct" + 0.040*"sale" + 0.034*"said" + 0.026*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.015*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.028442, rho=0.288675
INFO:gensim.models.ldamodel:-5.540 per-word bound, 46.5 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 11, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.061075337), np.float32(0.09839151)]
INFO:gensim.models.ldamodel:topic #0 (0.061): 0.051*"said" + 0.030*"japan" + 0.028*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.098): 0.071*"pct" + 0.040*"sale" + 0.034*"said" + 0.026*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.015*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.024177, rho=0.277350
INFO:gensim.models.ldamodel:-5.539 per-word bound, 46.5 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 12, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.058763735), np.float32(0.09575194)]
INFO:gensim.models.ldamodel:topic #0 (0.059): 0.051*"said" + 0.030*"japan" + 0.028*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.096): 0.071*"pct" + 0.040*"sale" + 0.034*"said" + 0.027*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.015*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.021074, rho=0.267261
INFO:gensim.models.ldamodel:-5.537 per-word bound, 46.4 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 13, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.056789085), np.float32(0.09339305)]
INFO:gensim.models.ldamodel:topic #0 (0.057): 0.051*"said" + 0.030*"japan" + 0.029*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"also"
INFO:gensim.models.ldamodel:topic #1 (0.093): 0.072*"pct" + 0.040*"sale" + 0.034*"said" + 0.027*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.015*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.018902, rho=0.258199
INFO:gensim.models.ldamodel:-5.536 per-word bound, 46.4 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 14, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.054613233), np.float32(0.090977535)]
INFO:gensim.models.ldamodel:topic #0 (0.055): 0.051*"said" + 0.030*"japan" + 0.029*"trade" + 0.018*"market" + 0.014*"import" + 0.014*"japanese" + 0.011*"official" + 0.011*"export" + 0.010*"ministry" + 0.009*"also"
INFO:gensim.models.ldamodel:topic #1 (0.091): 0.072*"pct" + 0.041*"sale" + 0.034*"said" + 0.027*"february" + 0.026*"january" + 0.022*"year" + 0.021*"billion" + 0.018*"dlrs" + 0.015*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.017958, rho=0.250000
INFO:gensim.utils:LdaModel lifecycle event {'msg': 'trained LdaModel<num_terms=500, num_topics=2, decay=0.5, chunksize=2000> in 0.30s', 'datetime': '2026-05-06T21:15:08.218805', 'gensim': '4.4.0', 'python': '3.12.13 (main, Apr 22 2026, 02:12:20) [GCC 14.2.0]', 'platform': 'Linux-6.12.76-linuxkit-aarch64-with-glibc2.41', 'event': 'created'}
INFO:gensim.topic_coherence.probability_estimation:using ParallelWordOccurrenceAccumulator<processes=9, batch_size=64> to estimate probabilities from sliding windows
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
INFO:gensim.topic_coherence.text_analysis:1 batches submitted to accumulate stats from 64 documents (1461 virtual)
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:serializing accumulator to return to master...
INFO:gensim.topic_coherence.text_analysis:accumulator serialized
INFO:gensim.topic_coherence.text_analysis:9 accumulators retrieved from output queue
INFO:gensim.topic_coherence.text_analysis:accumulated word occurrence stats for 2954 virtual documents
INFO:gensim.models.ldamodel:using autotuned alpha, starting with [np.float32(0.33333334), np.float32(0.33333334), np.float32(0.33333334)]
INFO:gensim.models.ldamodel:using symmetric eta at 0.3333333333333333
INFO:gensim.models.ldamodel:using serial LDA version on this node
INFO:gensim.models.ldamodel:running online (multi-pass) LDA training, 3 topics, 15 passes over the supplied corpus of 43 documents, updating model once every 43 documents, evaluating perplexity every 43 documents, iterating 50x with a convergence threshold of 0.001000
INFO:gensim.models.ldamodel:-6.811 per-word bound, 112.3 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 0, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.44916973), np.float32(0.50043464), np.float32(0.44145924)]
INFO:gensim.models.ldamodel:topic #0 (0.449): 0.055*"said" + 0.037*"pct" + 0.019*"year" + 0.018*"japan" + 0.014*"february" + 0.012*"trade" + 0.012*"dlrs" + 0.012*"market" + 0.011*"billion" + 0.011*"january"
INFO:gensim.models.ldamodel:topic #1 (0.500): 0.044*"pct" + 0.032*"said" + 0.028*"sale" + 0.025*"trade" + 0.022*"billion" + 0.018*"dlrs" + 0.016*"year" + 0.016*"january" + 0.015*"february" + 0.011*"surplus"
INFO:gensim.models.ldamodel:topic #2 (0.441): 0.059*"pct" + 0.039*"sale" + 0.039*"said" + 0.022*"january" + 0.022*"february" + 0.015*"analyst" + 0.013*"year" + 0.013*"mln" + 0.011*"gain" + 0.011*"rose"
INFO:gensim.models.ldamodel:topic diff=0.900183, rho=1.000000
INFO:gensim.models.ldamodel:-5.792 per-word bound, 55.4 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 1, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.17678842), np.float32(0.20659423), np.float32(0.22872609)]
INFO:gensim.models.ldamodel:topic #0 (0.177): 0.055*"said" + 0.025*"japan" + 0.024*"pct" + 0.019*"trade" + 0.016*"market" + 0.015*"year" + 0.013*"japanese" + 0.011*"import" + 0.011*"ministry" + 0.009*"export"
INFO:gensim.models.ldamodel:topic #1 (0.207): 0.037*"pct" + 0.030*"said" + 0.026*"trade" + 0.025*"billion" + 0.022*"dlrs" + 0.021*"year" + 0.016*"sale" + 0.013*"surplus" + 0.013*"deficit" + 0.011*"february"
INFO:gensim.models.ldamodel:topic #2 (0.229): 0.073*"pct" + 0.051*"sale" + 0.040*"said" + 0.030*"january" + 0.029*"february" + 0.014*"analyst" + 0.014*"retail" + 0.014*"gain" + 0.013*"rose" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.430736, rho=0.577350
INFO:gensim.models.ldamodel:-5.611 per-word bound, 48.9 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 2, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.11629474), np.float32(0.122730404), np.float32(0.17384604)]
INFO:gensim.models.ldamodel:topic #0 (0.116): 0.056*"said" + 0.029*"japan" + 0.023*"trade" + 0.019*"market" + 0.015*"pct" + 0.014*"japanese" + 0.013*"import" + 0.012*"ministry" + 0.011*"year" + 0.010*"official"
INFO:gensim.models.ldamodel:topic #1 (0.123): 0.034*"pct" + 0.029*"said" + 0.027*"billion" + 0.026*"trade" + 0.025*"year" + 0.024*"dlrs" + 0.015*"surplus" + 0.015*"deficit" + 0.011*"budget" + 0.010*"japan"
INFO:gensim.models.ldamodel:topic #2 (0.174): 0.078*"pct" + 0.054*"sale" + 0.040*"said" + 0.033*"january" + 0.032*"february" + 0.015*"retail" + 0.015*"rose" + 0.015*"gain" + 0.013*"analyst" + 0.013*"mln"
INFO:gensim.models.ldamodel:topic diff=0.282928, rho=0.500000
INFO:gensim.models.ldamodel:-5.546 per-word bound, 46.7 perplexity estimate based on a held-out corpus of 43 documents with 4431 words
INFO:gensim.models.ldamodel:PROGRESS: pass 3, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.0938081), np.float32(0.09722267), np.float32(0.1517641)]

Num topics:  2 | Coherence: 0.3625
Num topics:  3 | Coherence: 0.4541
Num topics:  4 | Coherence: 0.4483
Num topics:  5 | Coherence: 0.4024
Num topics:  6 | Coherence: 0.4228

## LDA Model Training

Latent Dirichlet Allocation (LDA) is a generative probabilistic model that discovers hidden topics in a corpus. Each document is modelled as a mixture of topics, and each topic is modelled as a mixture of words.

Key parameters:
- **num_topics**: number of topics to discover
- **passes**: number of full training passes over the corpus (more = better convergence)
- **iterations**: number of E-step iterations per document per pass
- **alpha**: document-topic distribution prior (`'auto'` = learned from data)
- **eta**: topic-word distribution prior (`'auto'` = learned from data)

In [9]:
# Train LDA model with 3 topics on sample data
lda_model = topic_utils.train_lda_model(
    corpus     = corpus,
    dictionary = dictionary,
    num_topics = 3,
    passes     = 10,      
    iterations = 100
)

# Print top 5 words per topic
for idx, topic in lda_model.print_topics(num_words=5):
    _LOG.info("Topic %d: %s", idx, topic)

INFO:gensim.models.ldamodel:using autotuned alpha, starting with [np.float32(0.33333334), np.float32(0.33333334), np.float32(0.33333334)]
INFO:gensim.models.ldamodel:using serial LDA version on this node
INFO:gensim.models.ldamodel:running online (multi-pass) LDA training, 3 topics, 10 passes over the supplied corpus of 43 documents, updating model once every 43 documents, evaluating perplexity every 0 documents, iterating 100x with a convergence threshold of 0.001000
INFO:gensim.models.ldamodel:PROGRESS: pass 0, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.31482893), np.float32(0.39284253), np.float32(0.26771745)]
INFO:gensim.models.ldamodel:topic #0 (0.315): 0.054*"said" + 0.036*"pct" + 0.020*"year" + 0.019*"japan" + 0.014*"trade" + 0.013*"market" + 0.011*"japanese" + 0.010*"february" + 0.009*"dlrs" + 0.009*"billion"
INFO:gensim.models.ldamodel:topic #1 (0.393): 0.043*"pct" + 0.032*"said" + 0.026*"sale" + 0.025*"trade" + 0.023*"billion" + 0.020*"dlrs" + 0.017*"year" + 0.016*"january" + 0.015*"february" + 0.011*"surplus"
INFO:gensim.models.ldamodel:topic #2 (0.268): 0.059*"pct" + 0.042*"said" + 0.041*"sale" + 0.023*"february" + 0.023*"january" + 0.017*"analyst" + 0.014*"mln" + 0.012*"gain" + 0.012*"year" + 0.010*"market"
INFO:gensim.models.ldamodel:topic diff=1.063104, rho=1.000000
INFO:gensim.models.ldamodel:PROGRESS: pass 1, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.15166374), np.float32(0.16033131), np.float32(0.17034459)]
INFO:gensim.models.ldamodel:topic #0 (0.152): 0.054*"said" + 0.025*"japan" + 0.024*"pct" + 0.019*"trade" + 0.017*"market" + 0.015*"year" + 0.014*"japanese" + 0.011*"import" + 0.010*"ministry" + 0.010*"official"
INFO:gensim.models.ldamodel:topic #1 (0.160): 0.037*"pct" + 0.030*"said" + 0.026*"trade" + 0.025*"billion" + 0.023*"dlrs" + 0.021*"year" + 0.016*"sale" + 0.013*"surplus" + 0.012*"deficit" + 0.012*"february"
INFO:gensim.models.ldamodel:topic #2 (0.170): 0.071*"pct" + 0.051*"sale" + 0.042*"said" + 0.030*"january" + 0.029*"february" + 0.016*"analyst" + 0.014*"gain" + 0.013*"mln" + 0.012*"retail" + 0.012*"rose"
INFO:gensim.models.ldamodel:topic diff=0.341443, rho=0.577350
INFO:gensim.models.ldamodel:PROGRESS: pass 2, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.11030018), np.float32(0.11817627), np.float32(0.13857302)]
INFO:gensim.models.ldamodel:topic #0 (0.110): 0.055*"said" + 0.028*"japan" + 0.023*"trade" + 0.019*"market" + 0.016*"pct" + 0.015*"japanese" + 0.013*"import" + 0.012*"ministry" + 0.011*"year" + 0.011*"official"
INFO:gensim.models.ldamodel:topic #1 (0.118): 0.034*"pct" + 0.029*"said" + 0.026*"billion" + 0.026*"trade" + 0.024*"dlrs" + 0.024*"year" + 0.015*"surplus" + 0.014*"deficit" + 0.011*"budget" + 0.011*"japan"
INFO:gensim.models.ldamodel:topic #2 (0.139): 0.076*"pct" + 0.055*"sale" + 0.041*"said" + 0.033*"january" + 0.032*"february" + 0.015*"gain" + 0.015*"analyst" + 0.014*"retail" + 0.014*"mln" + 0.014*"rose"
INFO:gensim.models.ldamodel:topic diff=0.254193, rho=0.500000
INFO:gensim.models.ldamodel:PROGRESS: pass 3, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.090725854), np.float32(0.097652934), np.float32(0.12674002)]
INFO:gensim.models.ldamodel:topic #0 (0.091): 0.056*"said" + 0.030*"japan" + 0.025*"trade" + 0.021*"market" + 0.015*"japanese" + 0.013*"import" + 0.013*"ministry" + 0.012*"pct" + 0.011*"official" + 0.011*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.098): 0.033*"pct" + 0.028*"said" + 0.027*"billion" + 0.026*"year" + 0.026*"trade" + 0.025*"dlrs" + 0.016*"surplus" + 0.016*"deficit" + 0.012*"budget" + 0.010*"japan"
INFO:gensim.models.ldamodel:topic #2 (0.127): 0.079*"pct" + 0.056*"sale" + 0.041*"said" + 0.034*"january" + 0.034*"february" + 0.015*"retail" + 0.015*"gain" + 0.015*"rose" + 0.014*"mln" + 0.014*"analyst"
INFO:gensim.models.ldamodel:topic diff=0.169622, rho=0.447214
INFO:gensim.models.ldamodel:PROGRESS: pass 4, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.078296304), np.float32(0.08353756), np.float32(0.11902827)]
INFO:gensim.models.ldamodel:topic #0 (0.078): 0.056*"said" + 0.031*"japan" + 0.026*"trade" + 0.021*"market" + 0.016*"japanese" + 0.014*"import" + 0.013*"ministry" + 0.012*"official" + 0.011*"tariff" + 0.011*"export"
INFO:gensim.models.ldamodel:topic #1 (0.084): 0.031*"pct" + 0.028*"year" + 0.028*"billion" + 0.028*"said" + 0.026*"trade" + 0.026*"dlrs" + 0.017*"surplus" + 0.016*"deficit" + 0.012*"budget" + 0.010*"economy"
INFO:gensim.models.ldamodel:topic #2 (0.119): 0.081*"pct" + 0.056*"sale" + 0.040*"said" + 0.035*"january" + 0.035*"february" + 0.016*"retail" + 0.016*"rose" + 0.015*"gain" + 0.015*"mln" + 0.013*"analyst"
INFO:gensim.models.ldamodel:topic diff=0.121133, rho=0.408248
INFO:gensim.models.ldamodel:PROGRESS: pass 5, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.07016598), np.float32(0.07371604), np.float32(0.11382446)]
INFO:gensim.models.ldamodel:topic #0 (0.070): 0.057*"said" + 0.032*"japan" + 0.027*"trade" + 0.021*"market" + 0.016*"japanese" + 0.014*"import" + 0.013*"ministry" + 0.012*"official" + 0.011*"tariff" + 0.011*"also"
INFO:gensim.models.ldamodel:topic #1 (0.074): 0.030*"pct" + 0.029*"year" + 0.028*"billion" + 0.027*"said" + 0.026*"dlrs" + 0.026*"trade" + 0.018*"surplus" + 0.017*"deficit" + 0.013*"budget" + 0.011*"government"
INFO:gensim.models.ldamodel:topic #2 (0.114): 0.082*"pct" + 0.056*"sale" + 0.040*"said" + 0.035*"january" + 0.035*"february" + 0.016*"rose" + 0.016*"retail" + 0.015*"gain" + 0.015*"mln" + 0.013*"billion"
INFO:gensim.models.ldamodel:topic diff=0.088558, rho=0.377964
INFO:gensim.models.ldamodel:PROGRESS: pass 6, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.06434736), np.float32(0.06690368), np.float32(0.10948942)]
INFO:gensim.models.ldamodel:topic #0 (0.064): 0.057*"said" + 0.032*"japan" + 0.027*"trade" + 0.022*"market" + 0.016*"japanese" + 0.014*"import" + 0.014*"ministry" + 0.013*"official" + 0.011*"also" + 0.011*"tariff"
INFO:gensim.models.ldamodel:topic #1 (0.067): 0.030*"year" + 0.029*"billion" + 0.029*"pct" + 0.027*"said" + 0.026*"dlrs" + 0.026*"trade" + 0.018*"surplus" + 0.018*"deficit" + 0.013*"budget" + 0.011*"government"
INFO:gensim.models.ldamodel:topic #2 (0.109): 0.083*"pct" + 0.056*"sale" + 0.039*"said" + 0.036*"january" + 0.035*"february" + 0.017*"rose" + 0.016*"retail" + 0.015*"mln" + 0.015*"gain" + 0.013*"billion"
INFO:gensim.models.ldamodel:topic diff=0.066971, rho=0.353553
INFO:gensim.models.ldamodel:PROGRESS: pass 7, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.05991878), np.float32(0.06180877), np.float32(0.105650775)]
INFO:gensim.models.ldamodel:topic #0 (0.060): 0.057*"said" + 0.032*"japan" + 0.028*"trade" + 0.022*"market" + 0.016*"japanese" + 0.014*"import" + 0.014*"ministry" + 0.013*"official" + 0.011*"also" + 0.011*"export"
INFO:gensim.models.ldamodel:topic #1 (0.062): 0.030*"year" + 0.029*"billion" + 0.027*"said" + 0.027*"pct" + 0.027*"dlrs" + 0.026*"trade" + 0.019*"surplus" + 0.018*"deficit" + 0.014*"budget" + 0.011*"government"
INFO:gensim.models.ldamodel:topic #2 (0.106): 0.084*"pct" + 0.056*"sale" + 0.039*"said" + 0.036*"january" + 0.035*"february" + 0.017*"rose" + 0.016*"retail" + 0.015*"mln" + 0.015*"gain" + 0.013*"billion"
INFO:gensim.models.ldamodel:topic diff=0.052195, rho=0.333333
INFO:gensim.models.ldamodel:PROGRESS: pass 8, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.056351174), np.float32(0.05729406), np.float32(0.10206188)]
INFO:gensim.models.ldamodel:topic #0 (0.056): 0.057*"said" + 0.033*"japan" + 0.028*"trade" + 0.022*"market" + 0.016*"japanese" + 0.014*"import" + 0.014*"ministry" + 0.013*"official" + 0.011*"also" + 0.011*"export"
INFO:gensim.models.ldamodel:topic #1 (0.057): 0.031*"year" + 0.029*"billion" + 0.027*"said" + 0.027*"dlrs" + 0.026*"trade" + 0.025*"pct" + 0.019*"surplus" + 0.018*"deficit" + 0.014*"budget" + 0.012*"government"
INFO:gensim.models.ldamodel:topic #2 (0.102): 0.084*"pct" + 0.056*"sale" + 0.039*"said" + 0.036*"january" + 0.035*"february" + 0.017*"rose" + 0.017*"retail" + 0.016*"mln" + 0.015*"gain" + 0.013*"billion"
INFO:gensim.models.ldamodel:topic diff=0.041152, rho=0.316228
INFO:gensim.models.ldamodel:PROGRESS: pass 9, at document #43/43
INFO:gensim.models.ldamodel:optimized alpha [np.float32(0.053428747), np.float32(0.053719062), np.float32(0.098850906)]
INFO:gensim.models.ldamodel:topic #0 (0.053): 0.057*"said" + 0.033*"japan" + 0.028*"trade" + 0.022*"market" + 0.016*"japanese" + 0.014*"import" + 0.014*"ministry" + 0.013*"official" + 0.011*"also" + 0.011*"export"
INFO:gensim.models.ldamodel:topic #1 (0.054): 0.031*"year" + 0.029*"billion" + 0.027*"said" + 0.027*"dlrs" + 0.026*"trade" + 0.024*"pct" + 0.019*"surplus" + 0.019*"deficit" + 0.014*"budget" + 0.012*"government"
INFO:gensim.models.ldamodel:topic #2 (0.099): 0.085*"pct" + 0.055*"sale" + 0.039*"said" + 0.036*"january" + 0.035*"february" + 0.017*"rose" + 0.017*"retail" + 0.016*"mln" + 0.015*"gain" + 0.013*"billion"
INFO:gensim.models.ldamodel:topic diff=0.031962, rho=0.301511
INFO:gensim.utils:LdaModel lifecycle event {'msg': 'trained LdaModel<num_terms=500, num_topics=3, decay=0.5, chunksize=2000> in 0.14s', 'datetime': '2026-05-06T21:15:31.721163', 'gensim': '4.4.0', 'python': '3.12.13 (main, Apr 22 2026, 02:12:20) [GCC 14.2.0]', 'platform': 'Linux-6.12.76-linuxkit-aarch64-with-glibc2.41', 'event': 'created'}
INFO:gensim.models.ldamodel:topic #0 (0.053): 0.057*"said" + 0.033*"japan" + 0.028*"trade" + 0.022*"market" + 0.016*"japanese"
INFO:gensim.models.ldamodel:topic #1 (0.054): 0.031*"year" + 0.029*"billion" + 0.027*"said" + 0.027*"dlrs" + 0.026*"trade"
INFO:gensim.models.ldamodel:topic #2 (0.099): 0.085*"pct" + 0.055*"sale" + 0.039*"said" + 0.036*"january" + 0.035*"february"
INFO:__main__:Topic 0: 0.057*"said" + 0.033*"japan" + 0.028*"trade" + 0.022*"market" + 0.016*"japanese"
INFO:__main__:Topic 1: 0.031*"year" + 0.029*"billion" + 0.027*"said" + 0.027*"dlrs" + 0.026*"trade"
INFO:__main__:Topic 2: 0.085*"pct" + 0.055*"sale" + 0.039*"said" + 0.036*"january" + 0.035*"february"

LDA model trained with 3 topics

## Topic Inspection and Labelling

After training, topics need to be inspected manually as LDA only clusters the documents into topics but doesn't provide human understandable labels. Topic inspection here includes inspecting top words and representative documents per topic, then manually assign human-readable labels.

Workflow:
- `inspect_topics()`: read output, decide labels
- Define `topic_labels` dict as `{topic_id: label}`
- `assign_topics()`: adds columns to dataframe

In [10]:
# Step 1 — inspect topics, no labels needed yet
topic_utils.inspect_topics(
    model       = lda_model,
    corpus      = corpus,
    df   = sample_df,
    title_column='title',
    num_topics  = 3,
    num_words   = 5,
    num_docs    = 5
)

=======================================================
  TOPIC 0
=======================================================

  Top 5 words:
    0.0570  - said
    0.0326  - japan
    0.0284  - trade
    0.0217  - market
    0.0163  - japanese

  Top 5 representative articles:
    1. [1.00] ECONOMIC SPOTLIGHT - TELECOM IS KEY JAPAN MINISTRY
    2. [1.00] JAPAN MINISTRY SAYS OPEN FARM TRADE WOULD HIT U.S.
    3. [1.00] JAPAN IN LAST-DITCH EFFORT TO AVERT TARIFFS
    4. [1.00] JAPANESE OFFICIAL TAKES DATA TO MICROCHIP TALKS
    5. [1.00] CANADA TO MONITOR STEEL IMPORTS, EXPORTS

=======================================================
  TOPIC 1
=======================================================

  Top 5 words:
    0.0308  - year
    0.0294  - billion
    0.0269  - said
    0.0269  - dlrs
    0.0256  - trade

  Top 5 representative articles:
    1. [1.00] DEFICIT CUTS SEEN UNABLE TO CURE TRADE DEFICIT
    2. [1.00] SOUTH KOREA MOVES TO SLOW GROWTH OF TRADE SURPLUS
    3. [1.00] JAPAN GIVEN LITTLE HOPE OF AVOIDING U.S. SANCTIONS
    4. [1.00] JAPAN GIVEN LITTLE HOPE OF AVOIDING U.S. SANCTIONS
    5. [1.00] G-7 ISSUES STATEMENT AFTER MEETING

=======================================================
  TOPIC 2
=======================================================

  Top 5 words:
    0.0851  - pct
    0.0555  - sale
    0.0389  - said
    0.0357  - january
    0.0355  - february

  Top 5 representative articles:
    1. [1.00] U.S. RETAIL SALES RISE MASKS WEAK TREND - ANALYSTS
    2. [1.00] FEBRUARY U.S. JOBS GAINS SHOW STRONGER ECONOMY
    3. [1.00] FEBRUARY U.S. RETAIL SALES NOT SIGN OF UPTURN
    4. [1.00] U.S. MARCH RETAIL SALES CUT BY LATE EASTER
    5. [1.00] U.S. RETAIL SALES RISE 4.1 PCT IN FEBRUARY

In [11]:
topic_labels = {
    0: 'Tech',
    1: 'Trade',
    2: 'Retail'
}

In [12]:
sample_df = topic_utils.assign_topics(
    df           = sample_df,
    corpus       = corpus,
    model        = lda_model,
    topic_labels = topic_labels
)

In [13]:
sample_df.head()

,title,content,topic_actual,cluster_id,topic_confidence,topic_label
0,ASIAN EXPORTERS FEAR DAMAGE FROM U.S.-JAPAN RIFT,Mounting trade friction between the U.S. And...,trade,0,0.7787,Tech
1,THAI TRADE DEFICIT WIDENS IN FIRST QUARTER,Thailand's trade deficit widened to 4.5 bill...,trade,2,0.9986,Retail
2,JAPAN MINISTRY SAYS OPEN FARM TRADE WOULD HIT ...,"Japan's Agriculture Ministry, angered by U.S...",trade,0,0.9992,Tech
3,SOUTH KOREA MOVES TO SLOW GROWTH OF TRADE SURPLUS,South Korea's trade surplus is growing too f...,trade,1,0.9993,Trade
4,JAPAN GIVEN LITTLE HOPE OF AVOIDING U.S. SANCT...,A top U.S. Official said Japan has little ch...,trade,1,0.9986,Trade

## Topic Visualization with pyLDAvis

pyLDAvis provides an interactive visualization of the LDA model with two panels:

- **Left panel** — intertopic distance map. Each bubble is a topic, size
  represents prevalence, distance represents similarity between topics
- **Right panel** — top 30 most relevant terms for the selected topic

Interpretation
- Well-separated bubbles: distinct, high-quality topics
- Overlapping bubbles: topics too similar 
- Setting **λ = 0.6** shows the most meaningful word rankings

In [14]:
topic_utils.get_pyldavis_visualization(lda_model, corpus, dictionary)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0      0.098046  0.113493       1        1  26.854909
1      0.081083 -0.088529       2        1  25.827989
2     -0.179129 -0.024964       3        1  47.317102, topic_info=         Term        Freq       Total Category  logprob  loglift
135      sale  122.000000  122.000000  Default  30.0000  30.0000
447   january   76.000000   76.000000  Default  29.0000  29.0000
111       pct  213.000000  213.000000  Default  28.0000  28.0000
403  february   77.000000   77.000000  Default  27.0000  27.0000
69      japan   49.000000   49.000000  Default  26.0000  26.0000
..        ...         ...         ...      ...      ...      ...
171      year   26.503464   68.792570   Topic3  -4.3708  -0.2055
35       dlrs   22.237442   59.034650   Topic3  -4.5463  -0.2280
332      data   11.606922   16.589756   Topic3  -5.1965   0.3911
233      rise   12.365140   21.584484   Topic3  -5.1332   0.1912
76       last   13.355711   30.343493   Topic3  -5.0561  -0.0723

[195 rows x 6 columns], token_table=      Topic      Freq       Term
term
456       3  0.892602  according
1         1  0.318860     action
1         2  0.744007     action
448       3  0.970587   adjusted
204       1  0.903106    already
...     ...       ...        ...
170       2  0.420421      would
170       3  0.152880      would
171       1  0.101755       year
171       2  0.508776       year
171       3  0.392484       year

[264 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 2, 3])